# Generated by Django 5.1.6 on 2026-09-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='is_notice_enabled',
            field=models.BooleanField(default=True, verbose_name='是否啟用網站公告'),
        ),
    ]
