# Generated by Django 5.1.6 on 2026-09-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_sitesettings_is_notice_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashFlowConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active_supplier",
                    models.CharField(
                        default="歐付寶",
                        max_length=50,
                        verbose_name="目前啟用的金流廠商",
                    ),
                ),
            ],
            options={
                "verbose_name": "全站金流選擇",
            },
        ),
        migrations.AlterModelOptions(
            name="cashflowsettings",
            options={"verbose_name": "金流廠商參數設定"},
        ),
        migrations.RenameField(
            model_name="cashflowsettings",
            old_name="type",
            new_name="env_type",
        ),
        migrations.RemoveField(
            model_name="cashflowsettings",
            name="cashflow_supplier",
        ),
        migrations.RemoveField(
            model_name="cashflowsettings",
            name="creditcard_payment",
        ),
        migrations.RemoveField(
            model_name="cashflowsettings",
            name="fee_percent",
        ),
        migrations.RemoveField(
            model_name="cashflowsettings",
            name="max_fee",
        ),
        migrations.RemoveField(
            model_name="cashflowsettings",
            name="min_fee",
        ),
        migrations.RemoveField(
            model_name="cashflowsettings",
            name="service_fee",
        ),
        migrations.RemoveField(
            model_name="cashflowsettings",
            name="shop_payment",
        ),
        migrations.RemoveField(
            model_name="cashflowsettings",
            name="virtual_payment",
        ),
        migrations.RemoveField(
            model_name="cashflowsettings",
            name="withdrawal_fee",
        ),
        migrations.RemoveField(
            model_name="cashflowsettings",
            name="withdrawal_status",
        ),
        migrations.AddField(
            model_name="cashflowsettings",
            name="has_credit_pay",
            field=models.BooleanField(default=False, verbose_name="有信用卡通道"),
        ),
        migrations.AddField(
            model_name="cashflowsettings",
            name="has_store_pay",
            field=models.BooleanField(default=True, verbose_name="有超商代碼通道"),
        ),
        migrations.AddField(
            model_name="cashflowsettings",
            name="has_virtual_pay",
            field=models.BooleanField(default=True, verbose_name="有虛擬帳號通道"),
        ),
        migrations.AddField(
            model_name="cashflowsettings",
            name="has_withdrawal",
            field=models.BooleanField(default=False, verbose_name="有出款服務"),
        ),
        migrations.AddField(
            model_name="cashflowsettings",
            name="service_fee_fixed",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="收款服務費(定額)",
            ),
        ),
        migrations.AddField(
            model_name="cashflowsettings",
            name="service_fee_max",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="收款服務費最高金額",
            ),
        ),
        migrations.AddField(
            model_name="cashflowsettings",
            name="service_fee_min",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="收款服務費最低金額",
            ),
        ),
        migrations.AddField(
            model_name="cashflowsettings",
            name="service_fee_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="收款服務費(%數)",
            ),
        ),
        migrations.AddField(
            model_name="cashflowsettings",
            name="supplier_name",
            field=models.CharField(
                default="歐付寶",
                max_length=50,
                unique=True,
                verbose_name="廠商名稱(如: 歐付寶, GSPay)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cashflowsettings",
            name="withdrawal_fee_fixed",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="出款服務費(定額)",
            ),
        ),
        migrations.AlterField(
            model_name="cashflowsettings",
            name="hash_iv",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Hash IV"
            ),
        ),
        migrations.AlterField(
            model_name="cashflowsettings",
            name="hash_key",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Hash Key"
            ),
        ),
        migrations.AlterField(
            model_name="cashflowsettings",
            name="merchant_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Merchant ID"
            ),
        ),
        migrations.AlterField(
            model_name="cashflowsettings",
            name="withdrawal_fee_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="出款服務費(%數)",
            ),
        ),
    ]
