# Generated by Django 5.1.6 on 2026-10-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_cashflowconfig_alter_cashflowsettings_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="id_verified",
            field=models.BooleanField(default=False, verbose_name="身分證是否驗證完成"),
        ),
        migrations.AlterField(
            model_name="client",
            name="is_tradable",
            field=models.BooleanField(default=False, verbose_name="是否可交易"),
        ),
    ]
