# Generated by Django 5.1.6 on 2026-09-14 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_link', models.CharField(max_length=255, verbose_name='商品圖片來源')),
                ('name', models.CharField(max_length=100, verbose_name='商品名稱(如: 新楓之檎幣)')),
                ('trade_type', models.CharField(choices=[('sell', '出售(平台賣給玩家)'), ('buy', '收購(平台向玩家買)')], default='sell', max_length=10, verbose_name='交易類型')),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='兌換比值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_exclusive', models.BooleanField(default=False, verbose_name='是否專屬商品')),
                ('is_soldout', models.BooleanField(default=False, verbose_name='是否售完')),
                ('single_digits_allowed', models.BooleanField(default=False, verbose_name='是否可下單個位數金額')),
                ('moq', models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='最小下單金額(MOQ)')),
                ('max_oq', models.DecimalField(decimal_places=2, default=10000, max_digits=10, verbose_name='最大下單金額(MaxOQ)')),
                ('exclusive_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.client', verbose_name='指定專屬會員')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True, verbose_name='訂單編號')),
                ('order_status', models.CharField(choices=[('pending', '待繳費'), ('paid', '已繳費/交易中'), ('transfered', '已移轉/已交貨'), ('completed', '交易完成'), ('cancelled', '已取消'), ('failed', '交易失敗/退款')], default='pending', max_length=20, verbose_name='訂單狀態')),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='訂單金額(TWD)')),
                ('game_coins', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='對應遊戲幣數量')),
                ('payment_info', models.TextField(blank=True, null=True, verbose_name='繳費資訊(如虛擬帳號/超商條碼)')),
                ('payment_source', models.CharField(blank=True, max_length=50, null=True, verbose_name='繳費管道(信用卡/超商/WebATM/LINE)')),
                ('game_id', models.CharField(max_length=50, verbose_name='伺服器/遊戲名稱')),
                ('game_account', models.CharField(max_length=50, verbose_name='玩家遊戲角色ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='訂單建立時間')),
                ('paid_time', models.DateTimeField(blank=True, null=True, verbose_name='繳費時間')),
                ('transfered_time', models.DateTimeField(blank=True, null=True, verbose_name='移轉/交貨時間')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.client', verbose_name='關聯會員')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tokens.product', verbose_name='購買商品')),
            ],
        ),
    ]
