# Generated by Django 5.1.6 on 2026-10-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_exclusive",
        ),
        migrations.AddField(
            model_name="product",
            name="game_type",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="遊戲類型"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, verbose_name="商品名稱"),
        ),
    ]
