# Generated by Django 5.1.6 on 2026-10-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0002_remove_product_is_exclusive_product_game_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="trade_type",
            field=models.CharField(
                choices=[("sell", "出售(玩家買幣)"), ("buy", "收購(玩家賣幣)")],
                default="sell",
                max_length=10,
                verbose_name="交易類型",
            ),
        ),
    ]
